resources:
  - ../../../config/broker/crd/broker.platform-mesh.io_acceptapis.yaml
  # These CRDs are not needed but mcmanager requires all CRDs at the moment (see #132)
  - ../../../config/broker/crd/broker.platform-mesh.io_migrationconfigurations.yaml
  - ../../../config/broker/crd/broker.platform-mesh.io_migrations.yaml
  - ../../../config/example/crd/example.platform-mesh.io_certificates.yaml

  # The issuer to issue certificates
  - issuer.yaml
  # The resource graph to project the generic api to cert-manager
  - rgd.yaml
  # The AcceptAPI for resource broker
  - acceptapi.yaml
